media:
  input: static/images
  output: /images
content:
  - name: posts
    label: Posts
    path: content/posts
    type: collection
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: author
        label: Author
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [programming, technology review, tutorial, productivity, technology, personal thoughts, macos, LLM, python, mac, opinion, ai, applescript, automation, data science, github, docker, writing tips, personal development, apple]
        required: true
      - name: title
        label: Title
        type: string
      - name: url
        label: Url
        type: string
      - name: snippet
        label: Snippet
        type: string
        required: false
      - name: body
        label: Body
        type: rich-text      
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
        fields: [ title, date ]
        primary: title
        sort: [ date, title ]
        default:
           search: ''
           sort: title
           order: desc
  - name: links
    label: links
    path: content/posts
    type: collection
    fields:
      - name: published
        label: Published
        type: boolean
        default: true
      - name: author
        label: Author
        type: string
        required: true
      - name: date
        label: Date
        type: date
        required: true
      - name: tags
        label: Tags
        type: select
        options:
          creatable: true
          multiple: true
          values: [programming, technology review, tutorial, productivity, technology, personal thoughts, macos, LLM, python, mac, opinion, ai, applescript, automation, data science, github, docker, writing tips, personal development, apple]
        required: true
      - name: title
        label: Title
        type: string
      - name: url
        label: Url
        type: string
      - name: link
        label: Link
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: link_title
        label: Link_Title
        type: string
      - name: snippet
        label: Snippet
        type: string
        required: false
      - name: body
        label: Body
        type: rich-text      
    filename: '{year}-{month}-{day}-{primary}.md'
    view:
        fields: [ title, date ]
        primary: title
        sort: [ date, title ]
        default:
           search: ''
           sort: title
           order: desc
