baseurl = "https://blog.lanzani.nl"
disablePathToLower = true
locale = "en-us"
title = "Technical inconsistencies blog"
theme = 'hugola'

[params]
Domain = "http://www.lanzani.nl"
Name = "lanzani.nl"
Rss = "https://blog.lanzani.nl/atom.xml"
Author = "Giovanni Lanzani"
role   = "MD, Xebia Data"
bio    = "Notes on tech, productivity, and, sometimes, politics."
lede   = "👋🏻 I'm Giovanni, MD at Xebia Data"
listHeading = "All posts"
listLede    = "Self-written, for good or for worse"
available  = "Available for advisory work, Q3 2026"
coords     = "52°22′N 4°53′E"
location   = "Amsterdam, NL"
version    = "v2.0 · 2026"

[params.sidebar]
search = "http://duckduckgo.com/?q=site%3Alanzani.nl"
blog = "/"
cv = "https://lanzani.nl/cv/"
publications = "https://lanzani.nl/publications/"
public = "https://lanzani.nl/public/"

[params.umami]
base_site = "https://umami.lanzani.nl"
base_site_id = "19952d0d-2825-4b1a-bb20-f1bca512b0a6"

[params.footer]
Contact = "mailto:giovanni at this domain?subject=feedback"
X = "http://twitter.com/gglanzani/"
GitHub = "http://github.com/gglanzani/"
Mastodon = "https://mastodon.social/@gla"
LinkedIn = "http://nl.linkedin.com/pub/giovanni-lanzani/24/618/195"


[outputs]
home = [ "HTML", "RSS" ]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "atom"

[menu]
  [[menu.main]]
    name = "writing"
    url  = "/posts/"
    weight = 1
  [[menu.main]]
    name = "cv"
    url  = "https://lanzani.nl/cv/"
    weight = 2
  [[menu.main]]
    name = "talks"
    url  = "https://lanzani.nl/public/"
    weight = 3
  [[menu.main]]
    name = "papers"
    url  = "https://lanzani.nl/publications/"
    weight = 4

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
      noclasses = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3

[module]
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "themes/hugola/assets"
    target = "assets"
  [[module.mounts]]
    source = "static/images"
    target = "assets/images"
