baseurl: http://blog.lanzani.nl
disablePathToLower: true
languageCode: en-us
title: Technical inconsistencies blog
params:
    Domain: "http://www.lanzani.nl"
    Name: "lanzani.nl"
    Blog: "/"
    CV: "http://www.lanzani.nl/cv/"
    Publications: "http://www.lanzani.nl/publications/"
